### PR TITLE
add circuit-breaking & egress

### PR DESCRIPTION
**Pull request by niqniqniqq**
1. In README.md, changed the Circuit Breaker section to explain about Connection Pool and Outlier Detection.
2.Added a description of Service Entries to README.md.
3.Added service-enrty.yaml.

### CODE REVIEW

**Comment by yokawasa** [comment]
@niqniqniqq thanks for the PR! I'll review and get back to you shortly
Anyway very sorry for the late response 🙇‍♂️ 🙇‍♂️ 🙇‍♂️

**Comment by yokawasa** [comment]
@niqniqniqq LGTM! Thanks for the contribution.

**Review by yokawasa — APPROVED** [review]

**Comment by niqniqniqq** [comment]
@yokawasa 
Thanks for the review!

**Comment by yokawasa** [comment]
let me go ahead to merge the PR!

**Pull request merged**
